name: "Frogbot Scan"
on: workflow_dispatch

permissions:
  contents: write
  pull-requests: write
  security-events: write
  # [Mandatory If using OIDC authentication protocol instead of JF_ACCESS_TOKEN]
  id-token: write
jobs:
  frogbot:
    runs-on: webgoat-mac
    strategy:
      matrix:
        # The repository scanning will be triggered periodically on the following branches.
        branch: ["main"]
    steps:
      - uses: jfrog/frogbot@v2.24.0
        env:
          # [Mandatory]
          # JFrog platform URL
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JF_GIT_BASE_BRANCH: ${{ matrix.branch }}
          JF_URL: https://${{ vars.JF_URL }}
        with:
          oidc-provider-name: webgoat-provider
